//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedArtefacts
{
    using System;
    using System.ComponentModel;
    
    
    public sealed class SchoolWrapper : INotifyPropertyChanged
    {
        
        private Models.School objectInstance;
        
        public SchoolWrapper(Models.School instance)
        {
            this.objectInstance = instance;
        }
        
        public string Name
        {
            get
            {
                return this.objectInstance.Name;
            }
            set
            {
                if (this.objectInstance.Name != value)
                {
                    this.objectInstance.Name = value;
                    this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Name"));
                }
            }
        }
        
        public System.Collections.Generic.ICollection<Models.Student> Students
        {
            get
            {
                return this.objectInstance.Students;
            }
            set
            {
                if (this.objectInstance.Students != value)
                {
                    this.objectInstance.Students = value;
                    this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Students"));
                }
            }
        }
        
        public System.Collections.Generic.ICollection<Models.Professor> Professors
        {
            get
            {
                return this.objectInstance.Professors;
            }
            set
            {
                if (this.objectInstance.Professors != value)
                {
                    this.objectInstance.Professors = value;
                    this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Professors"));
                }
            }
        }
        
        public System.Collections.Generic.ICollection<Models.Course> Courses
        {
            get
            {
                return this.objectInstance.Courses;
            }
            set
            {
                if (this.objectInstance.Courses != value)
                {
                    this.objectInstance.Courses = value;
                    this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Courses"));
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    }
}
